name: Apprentice Lineage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lineage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile apprentice contracts
        run: npx hardhat compile
