name: Apprentice Lineage Final

on:
  push:
    paths:
      - 'contracts/ApprenticeLineageFinal.sol'

jobs:
  lineage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile Apprentice Lineage Final
        run: npx hardhat compile
