name: Bootbark Test

on:
  push:
    paths:
      - 'test/testBootbark.js'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Bootbark tests
        run: npx hardhat test test/testBootbark.js
