name: Companion Bloom

on:
  push:
    paths:
      - 'companions.ts'
      - 'companions.json'
      - 'contracts/companions/**'

jobs:
  bloom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile companion contracts
        run: npx hardhat compile
