name: EMPAC Constellation Drift

on:
  push:
    paths:
      - 'contracts/EMPACConstellationDrift.sol'

jobs:
  drift:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile EMPAC constellation drift
        run: npx hardhat compile
