name: EMPAC Orbital Chant

on:
  push:
    paths:
      - 'contracts/EMPACOrbitalChant.sol'

jobs:
  chant:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile EMPAC orbital chant
        run: npx hardhat compile
