name: EMPAC Sanctum Chant

on:
  push:
    paths:
      - 'contracts/EMPACSanctumChant.sol'

jobs:
  chant:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile EMPAC Sanctum Chant
        run: npx hardhat compile
