name: EMPAC Orbital Node

on:
  push:
    paths:
      - 'contracts/EMPACOrbitalNode.sol'

jobs:
  ignite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile EMPAC Orbital Node
        run: npx hardhat compile
