name: EMPAC Sanctum Pulse

on:
  push:
    paths:
      - 'contracts/EMPACSanctumPulse.sol'

jobs:
  pulse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile EMPAC Sanctum Pulse
        run: npx hardhat compile
