name: Genesis Final Seal

on:
  push:
    paths:
      - 'contracts/GenesisFinalSeal.sol'

jobs:
  seal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile Genesis Final Seal
        run: npx hardhat compile
