name: Loader Daemon Summoner I

on:
  push:
    paths:
      - 'contracts/LoaderDaemonSummonerI.sol'

jobs:
  summon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile Loader Daemon Summoner I
        run: npx hardhat compile
