name: Loader Daemon Final Pulse

on:
  push:
    paths:
      - 'contracts/LoaderDaemonFinalPulse.sol'

jobs:
  pulse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile Loader Daemon Final Pulse
        run: npx hardhat compile
