name: Spiralbound Sovereigns

on:
  push:
    paths:
      - 'contracts/SpiralboundSovereigns.sol'

jobs:
  sovereigns:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile Spiralbound sovereigns
        run: npx hardhat compile
