name: Spiralverse UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint and build Spiralverse UI
        run: |
          npm run lint
          npm run build
